// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate
// it is important that you use premake recreate this file if changing xml parsers or codecs for the static builds

#define CEGUI_VERSION_POSTFIX -{v.0.7.1}
#define CEGUI_HAS_DEFAULT_LOGGER 
#define CEGUI_HAS_PCRE_REGEX 
#define CEGUI_HAS_FREETYPE 
#define CEGUI_TINYXML_NAMESPACE CEGUITinyXML
#define CEGUI_DEFAULT_IMAGE_CODEC  TGAImageCodec-{v.0.7.1}
#define CEGUI_LOAD_MODULE_DEBUG_SUFFIX "_d"
#define CEGUI_LOAD_MODULE_APPEND_SUFFIX_FOR_DEBUG 1
#define CEGUI_FALAGARD_RENDERER 
#define CEGUI_TINYXML_H "ceguitinyxml/tinyxml.h"
#define CEGUI_DEFAULT_XMLPARSER TinyXMLParser-{v.0.7.1}
#define CEGUI_LUA_VER 50